### ISSUE TITLE
数据保存方式解释 (原标题:About benefits)

### ISSUE THREAD

**Issue by an-Underpriviliged-ZJUer** [Lrunlin/puppeteer-juejin#1]
不错，掘金是个好网站

就是不知道爬下来为什么要用数据库的形式保存？

**Comment by Lrunlin** [comment]
> 不错，掘金是个好网站
> 
> 就是不知道爬下来为什么要用数据库的形式保存？

正如readme所讲，这个程序主要是为了给[博客项目使用](https://github.com/Lrunlin/blog)，爬取的文字直接存入博客网站的数据库，如果您有其他需求可以对其进行更改。

**Comment by Lrunlin** [comment]
最近会出一个剥离blog项目的，会以压缩包形式保存，可以关注一下
